# Instead of constantly writing strings everywhere, we add all possible properties for the scripts here


# general constants
_START_GENERAL = 0
YES = _START_GENERAL + 1
NO  = _START_GENERAL + 2

# orientation
__START_ORIENTATION = 100
X = __START_ORIENTATION + 1
Y = __START_ORIENTATION + 2

# channels
__START_CHANNELS = 200
CHANNEL_RED   = __START_CHANNELS + 1
CHANNEL_GREEN = __START_CHANNELS + 2
CHANNEL_BLUE  = __START_CHANNELS + 3

# list features
__START_LIST_FEATURES = 300
AVERAGE  = __START_LIST_FEATURES + 1
MEDIAN   = __START_LIST_FEATURES + 2
MAX      = __START_LIST_FEATURES + 3
MIN      = __START_LIST_FEATURES + 4
XOR      = __START_LIST_FEATURES + 5
MULTIPLY = __START_LIST_FEATURES + 6

LINE = 36
LEX = 37

# processing operations
__START_PROCESSING_OPS = 400
SIN        = __START_PROCESSING_OPS + 1
RAND_MOD_5 = __START_PROCESSING_OPS + 2



EACH_LINE_SMALL_TO_BIG = 50
EACH_LINE_BIG_TO_SMALL = 51
LEX_SMALL_TO_BIG = 52
LEX_BIG_TO_SMALL = 53

# sorting properties
SIMPLE = 100
RANDOM = 101
HIGHLIGHTS = 112
SHADOWS = 113

# blending modes
__START_BLEND_MODES = 50000

## darken blend modes
DARKEN        = __START_BLEND_MODES + 1
MULTIPLY      = __START_BLEND_MODES + 2
COLOR_BURN    = __START_BLEND_MODES + 3
LINEAR_BURN   = __START_BLEND_MODES + 4
DARKER_COLOR  = __START_BLEND_MODES + 5

## lighten blend modes
LIGHTEN       = __START_BLEND_MODES + 11
SCREEN        = __START_BLEND_MODES + 12
COLOR_DODGE   = __START_BLEND_MODES + 13
ADD           = __START_BLEND_MODES + 14
LIGHTER_COLOR = __START_BLEND_MODES + 15

## contrast blending modes
OVERLAY       = __START_BLEND_MODES + 21
SOFT_LIGHT    = __START_BLEND_MODES + 22
HARD_LIGHT    = __START_BLEND_MODES + 23
VIVID_LIGHT   = __START_BLEND_MODES + 24
LINEAR_LIGHT  = __START_BLEND_MODES + 25
PIN_LIGHT     = __START_BLEND_MODES + 26
HARD_MIX      = __START_BLEND_MODES + 27

## inversion blending modes
DIFFERENCE    = __START_BLEND_MODES + 31
EXCLUSION     = __START_BLEND_MODES + 32
SUBTRACT      = __START_BLEND_MODES + 33
DIVIDE        = __START_BLEND_MODES + 34